### ISSUE TITLE
已经使用了，但是具体怎么添加图片呀？

### ISSUE THREAD

**Issue by Chaaoo** [LifeAlsoIsGG/photos.lifeisgg.online#1]
已经使用了，但是具体怎么添加图片呀？

**Comment by draconidss** [comment]
啥意思，gridea的主题？我自己是把图片放在又拍云，调用又拍云存储服务里面图片的链接能转webp，在gridea设置域名那里我改成了又拍云的前缀。

**Comment by Chaaoo** [comment]
可以直接用https://cdn.jsdelivr.net/gh/tangxuchao/tuku/88ccf4454b9b7095f9be4e2b7becc78.jpg

**Comment by Chaaoo** [comment]
可以直接用这样子的域名吗

**Comment by draconidss** [comment]
哦我想起来了，加速的是js和css加速，图片我没弄加速，我是放在又拍云的，因为图片太多太大

**Comment by Chaaoo** [comment]
好吧，那没法通过jsdelivr添加图片么？只能用博文的封面来添加 图片？

**Comment by draconidss** [comment]
嗯对，你加博文封面的时候不是有外链选项嘛，直接加就行

**Comment by Chaaoo** [comment]
可以通过自定义配置实现么？用博文封面麻烦到爆炸，
自定义配置：
图片地址
图片名称
再就是有个BUG ，点博文，下方的about会自动弹出

**Comment by draconidss** [comment]
是有点麻烦
bug我去这个模板的官网看了，它也有，你图片多占完整个页就不会了
